version: '3.8'

services:

  db:
    container_name: postgres_container
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5444:5432"